name: 🐞 Bug Report
description: Report an Issue or Bug with the Package
title: '[Bug]: '
labels: ['bug']
assignees:
  - el-schneider
body:
  - type: markdown
    attributes:
      value: |
        Note: ⚠️ This addon is currently in pre-release development, please make sure you're always using the latest version, before filing an issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: I cannot currently do X thing because when I do, it breaks X thing.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce the bug
      description: How did this occur, please add any config values used and provide a set of reliable steps if possible.
      placeholder: When I do X I see Y.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please paste the *full* output of the `php please support:details` command. It gives us some context about your project.
      render: yaml
    validations:
      required: true
